### ISSUE TITLE
On mobile devices, the main character is just a black box

### ISSUE THREAD

**Issue by saricden** [saricden/no-place-like#5]
Title says it all.

**Probable cause:** WebGL texture size limit lower on lower power devices such as phones, therefore unable to render / load into memory / whatever dark witchcraft WebGL is doing. :shipit:

**Comment by tedbigham** [comment]
I made a pull request for this.  I still can't assign issues to myself though.

**Comment by saricden** [comment]
Hey awesome thanks man, will check out shortly! Thanks so much for
contributing dude!! Idk why you can't assign yourself issues, but I'll go
on a quick Google hunt before I sleep tonight!

**Comment by tedbigham** [comment]
I think in got it. I just opened the collaborator invite and accepted it. That unlocked a bunch of stuff.

**Comment by saricden** [comment]
👷👌

**Comment by saricden** [comment]
@tedbigham moved to _done_, feel free to close whenever you like :smile:
