### ISSUE TITLE
Double jump

### ISSUE THREAD

**Issue by saricden** [saricden/no-place-like#70]
`jay_al97: or make him double jump`

**Comment by jay51** [comment]
Hey @saricden , I found to approaches to do this. First 
    ```js  
// Player jump logic for up arrow key and w key
      if (up.isDown || W.isDown) {
        console.log("jumb");
        this.body.setVelocityY(-this.jumpHeight);
        up.isDown = null;
        W.isDown = null;
        setTimeout(() => {
          console.log("double jumb");
          if (up.isDown || W.isDown) {
            this.body.setVelocityY(-this.jumpHeight  *  2);
          }
        }, 350);
      }
```
The first one works but we have to play with setTimeout to find the perfect key down which 350 works perfect i think. 

Second approach is 

```js 
      // Player jump logic for up arrow key and w key
      if (up.isDown || W.isDown) {
        console.log("jumb");
        console.log(up.isDown, W.isDown);
        this.body.setVelocityY(-this.jumpHeight);
        setTimeout(() => {
          console.log("double jumb");
          if (up.isDown || W.isDown) {
            this.body.setVelocityY(-this.jumpHeight  *  2);
          }
        }, 250);
      }
```
works exactly like previous one but with this one, you need to press and hold the up key for 250ms.
Both approaches worked fine on my end. try it and let me know what you think

**Comment by jay51** [comment]
is this issue done? should i close it?

**Comment by saricden** [comment]
@jay51 hey duude, yes please :+1: we deviated a bit from the original double jump idea, but it inspired the system we're using now.

Thanks a ton for your hard work bro, if it weren't for your PR our jump system would still be super basic! :smile:
