### ISSUE TITLE
Gameplay Mechanics Overhaul (Kinda)

### ISSUE THREAD

**Issue by saricden** [saricden/no-place-like#82]
_Quoted from Twitch stream (thanks ViableClanMember!):_

**ViableClanMember**: for input, what if the whole left half of the screen is 'walk left', whole right is 'walk right' and press both is jump
**ViableClanMember**: maybe he could auto shoot
**ViableClanMember**: yeah shoot at closest, 100% hit rate
**ViableClanMember**: then it'd be more about positioning, tactics, timing
**ViableClanMember**: upgrade tree to upgrade his gun loads of tiers, tier 8 could be like a gattling gun
**ViableClanMember**: then shoulder mounted SAM missiles

_Further deets:_

Translate the primary "fight" gameplay mechanics from a traditional `platformer-shooter` to more of a `platformer-shooter-runner` so to speak. Effectively what we're changing is:

1. MC will auto aim & shoot at nearest enemy.
2. By bringing material to the `Engineer` NPC, it's possible to build new and stronger weapons (ultimately dealing more damage).
3. The touchscreen equivalent of our current "hold-to-charge-jump" mechanic will be to place a second thumb on the touchscreen, hold (like holding the up button), and release after charging ze jump.
4. Because we're removing the player-controlled aim mechanic, we are free to use the second thumb for :arrow_up: (3).

**Comment by saricden** [comment]
Thursday March 14th Agenda:

- [ ] Have MC face direction he's running in (once outside `aimThreshold`).
- [ ] Have MC auto-shoot once within the `shootThreshold`.
- [ ] Port "charge-jump" logic to mobile controls.
- [ ] Implement a "feature flags" system (which will enable the _player_ to enable and disable experimental features).
- [ ] Implement experimental feature No. 1: forward-facing targeting vs nearby targeting.

**Comment by saricden** [comment]
**NEXT STEPS**

Complete pointer debug circle system.

**Comment by medecau** [comment]
expanding on the above...
I think the idea is to draw circles centered on the mobile inputs
circles will be colored differently so as to distinguish from input1 and input2

**Comment by saricden** [comment]
Feels good.
